// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  api: create.doc("api", {"index.mdx": () => import("../content/api-reference/index.mdx?collection=api"), "github/getGitHubIssues.mdx": () => import("../content/api-reference/github/getGitHubIssues.mdx?collection=api"), "github/getGitHubStats.mdx": () => import("../content/api-reference/github/getGitHubStats.mdx?collection=api"), "github/index.mdx": () => import("../content/api-reference/github/index.mdx?collection=api"), "github/syncGitHubStats.mdx": () => import("../content/api-reference/github/syncGitHubStats.mdx?collection=api"), "health/healthCheck.mdx": () => import("../content/api-reference/health/healthCheck.mdx?collection=api"), "health/index.mdx": () => import("../content/api-reference/health/index.mdx?collection=api"), "roadmap/getRoadmap.mdx": () => import("../content/api-reference/roadmap/getRoadmap.mdx?collection=api"), "roadmap/getRoadmapFeatureById.mdx": () => import("../content/api-reference/roadmap/getRoadmapFeatureById.mdx?collection=api"), "roadmap/getRoadmapStats.mdx": () => import("../content/api-reference/roadmap/getRoadmapStats.mdx?collection=api"), "roadmap/index.mdx": () => import("../content/api-reference/roadmap/index.mdx?collection=api"), "users/getCurrentUser.mdx": () => import("../content/api-reference/users/getCurrentUser.mdx?collection=api"), "users/index.mdx": () => import("../content/api-reference/users/index.mdx?collection=api"), "users/updateUserName.mdx": () => import("../content/api-reference/users/updateUserName.mdx?collection=api"), }),
  docs: create.doc("docs", {"index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "overview.mdx": () => import("../content/docs/overview.mdx?collection=docs"), "getting-started/docker-deployment.mdx": () => import("../content/docs/getting-started/docker-deployment.mdx?collection=docs"), "getting-started/local-setup.mdx": () => import("../content/docs/getting-started/local-setup.mdx?collection=docs"), "getting-started/quick-start.mdx": () => import("../content/docs/getting-started/quick-start.mdx?collection=docs"), "operations/environment-variables.mdx": () => import("../content/docs/operations/environment-variables.mdx?collection=docs"), "operations/service-status.mdx": () => import("../content/docs/operations/service-status.mdx?collection=docs"), "user-guides/exporting-and-sharing.mdx": () => import("../content/docs/user-guides/exporting-and-sharing.mdx?collection=docs"), "user-guides/resume-templates.mdx": () => import("../content/docs/user-guides/resume-templates.mdx?collection=docs"), }),
};
export default browserCollections;